apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: MySecondApp
  namespace: argocd
spec:
  # Project description
  description: A supper dupper first project

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'

  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: guestbook
    server: https://kubernetes.default.svc

  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: MySecondApp-prd
  namespace: argocd
spec:
  project: MySecondApp
  environment: prd
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: mysecondapp
    helm:
      valueFiles: prd/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prd
